-- Phase 1 core schema: the source registry, normalized items, and fetch runs.
--
-- Conventions:
--   * Primary keys are UUIDs generated by the application (UUIDv7, time-ordered).
--   * Timestamps are timestamptz; the application works in UTC.
--   * Open-ended vocabularies that grow with new adapters (source type, item
--     kind) are format-checked here and validated against known values in Go,
--     so adding a source type never requires a schema migration.
--   * Closed lifecycle vocabularies (statuses, triggers) are enforced here.
--   * AI-derived data (summaries, scores, topics, clusters) and user data will
--     live in their own tables in later phases; nothing here needs rewriting.

-- +goose Up

CREATE TABLE sources (
    id                         uuid        PRIMARY KEY,
    slug                       text        NOT NULL,
    name                       text        NOT NULL,
    type                       text        NOT NULL,
    url                        text        NOT NULL DEFAULT '',
    status                     text        NOT NULL DEFAULT 'active',
    priority                   integer     NOT NULL DEFAULT 0,
    -- Adapter-specific settings, validated by the adapter.
    config                     jsonb       NOT NULL DEFAULT '{}',
    -- Adapter-owned cursor/watermark, persisted only after successful fetches.
    state                      jsonb       NOT NULL DEFAULT '{}',
    -- Minimum time between fetches: anti-hammering now, scheduler input later.
    min_fetch_interval_seconds integer     NOT NULL DEFAULT 600,
    last_fetch_at              timestamptz,
    last_success_at            timestamptz,
    last_failure_at            timestamptz,
    last_error                 text        NOT NULL DEFAULT '',
    consecutive_failures       integer     NOT NULL DEFAULT 0,
    created_at                 timestamptz NOT NULL DEFAULT now(),
    updated_at                 timestamptz NOT NULL DEFAULT now(),
    retired_at                 timestamptz,

    CONSTRAINT sources_slug_key              UNIQUE (slug),
    CONSTRAINT sources_slug_format           CHECK (slug ~ '^[a-z0-9][a-z0-9-]{0,62}$'),
    CONSTRAINT sources_name_not_blank        CHECK (btrim(name) <> ''),
    CONSTRAINT sources_type_format           CHECK (type ~ '^[a-z][a-z0-9_]{0,31}$'),
    CONSTRAINT sources_status_valid          CHECK (status IN ('active', 'paused', 'retired')),
    CONSTRAINT sources_config_is_object      CHECK (jsonb_typeof(config) = 'object'),
    CONSTRAINT sources_state_is_object       CHECK (jsonb_typeof(state) = 'object'),
    CONSTRAINT sources_min_interval_nonneg   CHECK (min_fetch_interval_seconds >= 0),
    CONSTRAINT sources_failures_nonneg       CHECK (consecutive_failures >= 0),
    CONSTRAINT sources_retired_at_consistent CHECK ((status = 'retired') = (retired_at IS NOT NULL))
);

CREATE TABLE items (
    id             uuid        PRIMARY KEY,
    source_id      uuid        NOT NULL REFERENCES sources (id) ON DELETE RESTRICT,
    -- Stable identifier within the source (HN objectID, arXiv id without
    -- version, GitHub repository id). Same-source dedup key.
    external_id    text        NOT NULL,
    kind           text        NOT NULL,
    title          text        NOT NULL,
    description    text        NOT NULL DEFAULT '',
    -- The link exactly as the source provided it.
    url            text        NOT NULL,
    canonical_url  text        NOT NULL,
    -- sha256(canonical_url): the cross-source dedup key.
    url_hash       bytea       NOT NULL,
    -- e.g. the HN comments page when url points elsewhere.
    discussion_url text        NOT NULL DEFAULT '',
    authors        text[]      NOT NULL DEFAULT '{}',
    tags           text[]      NOT NULL DEFAULT '{}',
    -- sha256 of normalized title + description: change detection.
    content_hash   bytea       NOT NULL,
    -- Source-specific data (stars, points, comment counts, pdf url, ...).
    metadata       jsonb       NOT NULL DEFAULT '{}',
    -- Set when an item from another source with the same url_hash was stored
    -- first. Duplicates are kept (they carry signal) but hidden from the feed.
    duplicate_of   uuid        REFERENCES items (id) ON DELETE SET NULL,
    published_at   timestamptz,
    discovered_at  timestamptz NOT NULL DEFAULT now(),
    last_seen_at   timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    -- Feed ordering key: never NULL, so keyset pagination stays simple.
    feed_at        timestamptz GENERATED ALWAYS AS (COALESCE(published_at, discovered_at)) STORED,

    CONSTRAINT items_source_external_key   UNIQUE (source_id, external_id),
    CONSTRAINT items_external_id_not_blank CHECK (btrim(external_id) <> ''),
    CONSTRAINT items_kind_format           CHECK (kind ~ '^[a-z][a-z0-9_]{0,31}$'),
    CONSTRAINT items_title_not_blank       CHECK (btrim(title) <> ''),
    CONSTRAINT items_url_not_blank         CHECK (btrim(url) <> ''),
    CONSTRAINT items_canonical_not_blank   CHECK (btrim(canonical_url) <> ''),
    CONSTRAINT items_url_hash_sha256       CHECK (octet_length(url_hash) = 32),
    CONSTRAINT items_content_hash_sha256   CHECK (octet_length(content_hash) = 32),
    CONSTRAINT items_metadata_is_object    CHECK (jsonb_typeof(metadata) = 'object'),
    CONSTRAINT items_not_own_duplicate     CHECK (duplicate_of <> id)
);

-- Default feed: newest first, duplicates hidden.
CREATE INDEX items_feed_idx ON items (feed_at DESC, id DESC) WHERE duplicate_of IS NULL;
-- Feed filtered by source.
CREATE INDEX items_source_feed_idx ON items (source_id, feed_at DESC, id DESC);
-- Cross-source dedup lookups.
CREATE INDEX items_url_hash_idx ON items (url_hash);
-- "Also seen on" lookups and FK maintenance.
CREATE INDEX items_duplicate_of_idx ON items (duplicate_of) WHERE duplicate_of IS NOT NULL;
-- Tag filtering.
CREATE INDEX items_tags_idx ON items USING gin (tags);

CREATE TABLE fetch_runs (
    id              uuid        PRIMARY KEY,
    source_id       uuid        NOT NULL REFERENCES sources (id) ON DELETE RESTRICT,
    trigger         text        NOT NULL,
    status          text        NOT NULL DEFAULT 'running',
    started_at      timestamptz NOT NULL DEFAULT now(),
    finished_at     timestamptz,
    items_fetched   integer     NOT NULL DEFAULT 0,
    items_inserted  integer     NOT NULL DEFAULT 0,
    items_updated   integer     NOT NULL DEFAULT 0,
    items_unchanged integer     NOT NULL DEFAULT 0,
    -- Inserted, but linked to an existing item from another source.
    items_duplicate integer     NOT NULL DEFAULT 0,
    error           text        NOT NULL DEFAULT '',

    CONSTRAINT fetch_runs_trigger_valid       CHECK (trigger IN ('api', 'cli', 'scheduler')),
    CONSTRAINT fetch_runs_status_valid        CHECK (status IN ('running', 'succeeded', 'failed')),
    CONSTRAINT fetch_runs_finished_consistent CHECK ((status = 'running') = (finished_at IS NULL)),
    CONSTRAINT fetch_runs_counts_nonneg       CHECK (
        items_fetched >= 0 AND items_inserted >= 0 AND items_updated >= 0
        AND items_unchanged >= 0 AND items_duplicate >= 0
    )
);

-- At most one in-flight fetch per source, enforced by the database.
CREATE UNIQUE INDEX fetch_runs_one_running_per_source ON fetch_runs (source_id) WHERE status = 'running';
-- Run history per source.
CREATE INDEX fetch_runs_source_started_idx ON fetch_runs (source_id, started_at DESC);

-- +goose Down

DROP TABLE fetch_runs;
DROP TABLE items;
DROP TABLE sources;
